server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/JCR_salon
    username: postgres
    password: juanpablo

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: JCR-Salon

# email:

  mail:
    host: smtp.gmail.com
    port: 587
    username: pachoregino2001@gmail.com
    password: krkiteozoxxockat
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
            required: false


#             var transport = nodemailer.createTransport({
#   host: "sandbox.smtp.mailtrap.io",
#   port: 2525,
#   auth: {
#     user: "73b7be50601c1e",
#     pass: "********12f2"
#   }
# });

# var transport = nodemailer.createTransport({
#   host: "sandbox.smtp.mailtrap.io",
#   port: 2525,
#   auth: {
#     user: "73b7be50601c1e",
#     pass: "6f2c7a254f12f2"
#   }
# });