server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/JCR_salon
    username: postgres
    password: juanpablo

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: JCR-Salon
  